networks:
  nodejs2024q3_network:
    driver: bridge

services:
  database:
    # image: postgres:latest
    container_name: hl_db
    # environment:
    #   POSTGRES_DB: "${POSTGRES_DB}"
    #   POSTGRES_USER: "${POSTGRES_USER}"
    #   POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    networks:
      - nodejs2024q3_network
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hl_app
    # environment:
    #   DATABASE_URL: "${DATABASE_URL}"
    #   PORT: "${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nodejs2024q3_network
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    env_file:
      - .env
    restart: always

volumes:
  db_data:
  db_logs:
