networks:
  nodejs2024q3_network:
    driver: bridge

services:
  database:
    image: postgres:latest
    container_name: nodejs2024q3_postgres_container
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    networks:
      - nodejs2024q3_network
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always

  app:
    build: .
    container_name: nodejs2024q3_app_container
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:{DB_PORT}/${POSTGRES_DB}"
      NODE_ENV: development
      PORT: "${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nodejs2024q3_network
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    restart: always

volumes:
  db_data:
  db_logs:
